### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by potherca** [themccallister/craft#5]
Pretty please? :smile: 

To avoid confusion for folks looking for "craft" on github it would be a good idea to give this repository a name more closely describing its content rather than the generic name it now has.

**Comment by themccallister** [comment]
Not sure if I would be willing to rename it as it would break the composer installation. 

Since the Craft repository is a reference only I'm again not sure if its worth changing. Also, most plugins are usually hinted with the name "craft" so searching is going to be hit or miss.

Thoughts?

**Comment by potherca** [comment]
Typically the project (and/repo) name would mirror the namespace (or vice-versa) so `craft-cli` seems a nice fit. 

Whether or not the gain of changing the repo name is worth the pain is a different story... 
As the readme file does not have a "usage" section offering more details on what the "composer install" entails I can't rightfully comment on that.  However, if this project offers functionality that truly benefits the Craft community at large I would strongly advocate trying to get this moved to the Pixel and Tonic organisation on github (or better yet, create a separate organisation for Craft CMS, but that's another matter entirely). In such a scenario the confusion would be even larger if the repo name was left intact.

As a side note, it would seems more worthwhile to invest in a composer-installer rather than a "custom" installer (why re-build infrastructure that is already there?) but that is also slightly besides the point, I guess.

In regards to Craft plugins, if a common vocabulary is used (like symfony plugins use "bundle", silex uses "ServiceProvider", etc.) it should be a lot less hit-and-miss. If this is a common problem within the community it might be something worth actively evangelizing but I have not used enough vendor plugins to comment on that matter. 

For the largest part I guess it boils down to how much value one places on semantics and developer experience. If these are deemed less important than there's no strong argument in favour of investing time/effort into such issues. Personally I tend te be a bit of a stickler for details, but you may have already gather that much :wink:

**Comment by themccallister** [comment]
I understand your concerns, I'm also a stickler for details which is why I renamed this repository several times before "announcing" it. 

However, people are actively using it, even though its not on a massive scale, I am more a stickler for things not breaking and changing it now would in fact break usage.

**Comment by potherca** [comment]
Agreed. Filing this under "we'll cross that bridge when we come to it". Thanks for your reply!
