### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by Chrisedmo** [themccallister/craft#9]
I'm trying to set this up on my mac, and I'm getting the following errors when trying to run the global require command… any ideas what could be causing this. Thanks?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package themccallister/craft could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by themccallister** [comment]
I'm having some issues with Packagist and composer, let me see if I can correct those really quick.

**Comment by jasonmccallister** [comment]
I just updating the `composer.json` and pushed version 1.3.1. 

This should solve the issue, let me know if you still have the same problem.

**Comment by jasonmccallister** [comment]
I'm going to close this issue out.

**Comment by Chrisedmo** [comment]
Great - sorry I didn't reply to your question I was on holiday. But I can now confirm I am able to use this. Thanks.
